networks:
  app-tier:
    driver: bridge

services:
#  postgresql:
#    image: "postgres:16.2-alpine"
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_DATABASE=postgres
#      - POSTGRES_USER=postgres
#      - PGUSER=postgres
#      - POSTGRES_PASSWORD=postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-q", "-U", "postgres", "-d", "postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
  jaeger:
    image: "jaegertracing/all-in-one:1.57"
    ports:
      - "16686:16686" # UI
      - "4317:4317" # Ingestion port
      - "4318:4318" # Ingestion port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  seq:
    image: "datalust/seq:2024.3"
    restart: unless-stopped
    ports: 
      - "5342:80" # UI
      - "5341:5341" # Ingestion port
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./data/seq:/data